import { readFileSync } from 'fs';
console.log("# PACKAGE.JSON")
console.log("# PACKAGE.JSON")
console.log("# PACKAGE.JSON")
console.log("# PACKAGE.JSON")
console.log("# PACKAGE.JSON")
console.log("# PACKAGE.JSON")
console.log("# PACKAGE.JSON")
console.log(readFileSync(`./package.json`).toString())
console.log("# END OF PACKAGE.JSON")
console.log("# END OF PACKAGE.JSON")
console.log("# END OF PACKAGE.JSON")
console.log("# END OF PACKAGE.JSON")
console.log("# END OF PACKAGE.JSON")
console.log("# END OF PACKAGE.JSON")
console.log("# -------------------------------------------------------------------- #")
console.log("# -------------------------------------------------------------------- #")
console.log("# -------------------------------------------------------------------- #")
console.log("# -------------------------------------------------------------------- #")
console.log("# -------------------------------------------------------------------- #")
console.log("# -------------------------------------------------------------------- #")
console.log("# -------------------------------------------------------------------- #")
console.log("# -------------------------------------------------------------------- #")
console.log("# -------------------------------------------------------------------- #")
console.log("# PACKAGE-LOCK.JSON")
console.log("# PACKAGE-LOCK.JSON")
console.log("# PACKAGE-LOCK.JSON")
console.log("# PACKAGE-LOCK.JSON")
console.log("# PACKAGE-LOCK.JSON")
console.log("# PACKAGE-LOCK.JSON")
console.log("# PACKAGE-LOCK.JSON")
console.log(readFileSync(`./package-lock.json`).toString())
console.log("# END OF PACKAGE-LOCK.JSON")
console.log("# END OF PACKAGE-LOCK.JSON")
console.log("# END OF PACKAGE-LOCK.JSON")
console.log("# END OF PACKAGE-LOCK.JSON")
console.log("# END OF PACKAGE-LOCK.JSON")
console.log("# END OF PACKAGE-LOCK.JSON")
