
name: Detect Mods

on:
  push:
    branches: ["main"]
  schedule:
    - cron:  '*/5 * * * *'

  workflow_dispatch:


jobs:
  
  detect:
    strategy:
      matrix:
        node-version: [20.x]
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout This Repository
        uses: actions/checkout@v3
        with:
          path: code
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Run ci command from npm
        run: |
          cd ./code/
          npm ci

      - name: Run Detector
        id: run_de
        run: |
          cd ./code/
          npm run deploy
      - name: Update Index
        if: steps.run_de.outputs.update_index == 'true'
        id: theGit
        run: |
          echo "mum=false" >> $GITHUB_OUTPUT
          git config --global user.email "${{ secrets.GEODE_BOT_EMAIL }}"
          git config --global user.name "Coop's Bot"
          git clone https://github.com/coopeeo/geodemodindex.git

          cd geodemodindex
          git config --local user.email "${{ secrets.GEODE_BOT_EMAIL }}"
          git config --local user.name "Coop's Bot"
          git config pull.rebase false
          git remote set-url origin "https://${{ secrets.GEODE_BOT_PUSH_BIN_TOKEN }}@github.com/coopeeo/geodemodindex.git"
          git remote add upstream "https://github.com/geode-sdk/mods.git"
          git pull origin mods
          git fetch upstream
          git checkout mods
          git rebase upstream/main
          git push -f origin mods || true
          echo "mum=true" >> $GITHUB_OUTPUT
      - name: Update Coop's Geode Website (via action)
        if: steps.run_de.outputs.update_index == 'true' && steps.theGit.outputs.mum == 'true'
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GEODE_BOT_PUSH_BIN_TOKEN }}
          script: |
            await github.rest.actions.createWorkflowDispatch({
                owner: 'coopeeo',
                repo: 'geode-website',
                workflow_id: 'build.yml',
                ref: 'main'
            })
      - name: Run Python
        if: steps.run_de.outputs.update_index == 'true'
        id: runit
        shell: bash
        run: |
          python3 code/sendupdate.py
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
          DISCORD_WEBHOOK_URL2: ${{ secrets.DISCORD_WEBHOOK_URL_2 }}
          DISCORD_WEBHOOK_URL3: ${{ secrets.DISCORD_WEBHOOK_URL_3 }}
          DISCORD_WEBHOOK_URL4: ${{ secrets.DISCORD_WEBHOOK_URL_4 }}
          ROLE_ID: ${{ secrets.ROLE_ID }}
          ROLE_ID2: ${{ secrets.ROLE_ID_2 }}
          THE_OBJECT: ${{ steps.run_de.outputs.list_indexx }}
          THE_OBJECT2: ${{ steps.run_de.outputs.list_index }}
          THE_OBJECT3: ${{ steps.run_de.outputs.list_indexxx }}
          THE_OBJECT4: ${{ steps.run_de.outputs.list_indexxxx }}
          NTFY_GROUP: ${{ secrets.NTFY_GROUP }}

      # dont use unless installing packages
      #- name: Show Package Lock and Package 
      #  run: |
      #    cd ./code/
      #    node spitoutthepackagelock.js

